version: '3.8'

services:
  giftvoucher:
    image: giftvoucher:latest
    environment:
      - OUTPUT_DIR=/app/Output
    volumes:
      - gift_voucher_output:/app/Output
    command: python main.py

volumes:
  gift_voucher_output:
    external: true